### ISSUE TITLE
How to use the saved model without retraining?

### ISSUE THREAD

**Issue by adityakrshnn** [mohamedameen93/German-Traffic-Sign-Classification-Using-TensorFlow#1]
I am trying to use the model but VGGNet_Model requires the VGGNet function which are the layers itself. Can you provide me the steps to use the pretrained model?

**Comment by tahaahiskali** [comment]
Hi mohammed;
I need  "**lenet.config**" file to use  "Tensorflow Object Detection API"
How can I write? or where can I find it?

_example_

 SSD with Mobilenet v1, configured for Oxford-IIIT Pets Dataset.
 Users should configure the fine_tune_checkpoint field in the train config as
 well as the label_map_path and input_path fields in the train_input_reader and
 eval_input_reader. Search for "PATH_TO_BE_CONFIGURED" to find the fields that
 should be configured.

model {
  ssd {
    num_classes: 2
    box_coder {
      faster_rcnn_box_coder {
        y_scale: 10.0
        x_scale: 10.0
        height_scale: 5.0
        width_scale: 5.0
      }
    }
    matcher {
      argmax_matcher {
        matched_threshold: 0.5
        unmatched_threshold: 0.5
        ignore_thresholds: false
        negatives_lower_than_unmatched: true
        force_match_for_each_row: true
      }
    }
    similarity_calculator {
      iou_similarity {
      }
    }
...

**Comment by mrgrin** [comment]
Same issue.
Trying to use pre-trained graph but keep getting errors and program requires VGGNet class.
Any updates?

**Comment by mohamedameen-io** [comment]
Sorry guys I didn't have much time to look into the issue, and unfortunately I don't think I'd be able to check it in the foreseeable future.
